fixed:
  dataset: zinc
  config_root: zinc_pna
  log_path: './logs'
  voting: 5

  sample_configs:
    sample_policy: node
    sample_k: -1
    num_subgraphs: 10
    remove_node: False
    add_full_graph: True
    sample_with_esan: False

  imle_configs: null