common:
  model: pna
  normalize_label: False
  hid_size: 128
  edge_hid_size: 64
  lr: 1.e-3
  lr_steps: [ 400, 600 ]
  patience: 100
  dropout: 0.
  reg: 0.
  num_convlayers: 4
  gnn_jk: 'residual'
  batch_size: 128
  min_epochs: 700
  max_epochs: 1000
  data_path: './datasets'
  debug: False
  num_runs: 5