fixed:
  dataset: 'zinc'
  log_path: './logs'
  voting: 5

  model: 'dsnet'
  gnn_type: 'zincgin'
  num_convlayers: 4
  hid_size: 64
  batch_size: 128

  jk: 'concat'
  channels: [96, 96]

  sample_configs:
    sample_policy: khop_global
    sample_k: 3
    num_subgraphs: 10
    remove_node: False
    add_full_graph: True
    sample_with_esan: False

  imle_configs:
    embd_lr: 1.e-3
    reg_embd: 0.
    imle_sample_rand: False
    micro_batch_embd: 1
    norm_logits: False
    noise_scale: 1.
    beta: 10.
    aux_loss_weight: 10.