common:
  model: ogb_gin
#  gnn_type: gin
  dataset: ogbg-moltox21
  dropout: 0.5
  hid_size: 300
  lr: 1.e-3
  lr_steps: [ 10000, 99999 ]
  patience: 100
#  jk: 'last'
  reg: 0.
  num_convlayers: 5
#  channels: [64, 64]
  batch_size: 128
  min_epochs: 100
  max_epochs: 300
  data_path: './datasets'
  debug: False
  num_runs: 5