fixed:
  dataset: zinc
  log_path: './logs'
  voting: 5

  sample_configs:
    sample_policy: khop_dual
    sample_k: 1
    num_subgraphs: 3
    remove_node: True
    add_full_graph: True
    sample_with_esan: False

  imle_configs: null
