fixed:
  dataset: ogbg-molesol
  log_path: './logs'
  voting: 5
  lr_steps: [ 150, 300 ]
  min_epochs: 300
  max_epochs: 500

  sample_configs:
    sample_policy: edge
    sample_k: -3
    num_subgraphs: 10
    remove_node: False
    add_full_graph: True
    sample_with_esan: False

  imle_configs:
    embd_lr: 1.e-3
    reg_embd: 0.
    imle_sample_rand: False
    micro_batch_embd: 1
    norm_logits: False
    noise_scale: 1.
    beta: 1.
    aux_loss_weight: 10.
